### ISSUE TITLE
display flickering on RG350m

### ISSUE THREAD

**Issue by LoveBootCaptain** [skipmeister123/gcwconnect#2]
i quickly installed it to my rg350m (with metallic case). it has a 640x480 screen. launching will let the display flicker like crazy.

i just changed `surface = pygame.display.set_mode((320,240))` to `surface = pygame.display.set_mode((640,480))` and rebuild the .opk file. this is a dirty hotfix, cause the interface ist just 1/4 the size but you can add you access point without any issue. X and Y buttons seems to swapped as well on the rg350m.

maybe you can use the pygame builtin function to get the display size to support both models?
```python
w, h = pygame.display.get_surface().get_size()
surface = pygame.display.set_mode((w, h))
```
doesn't solve the swapped buttons... but maybe you can hock that also to the display size. If display size is 320x240 use X/Y else use Y/X...

hope that helps to improve your nice little pygame app ;)

if you need help, just ask... maybe i find time to make a PR

kind regards from berlin

**Comment by skipmeister123** [comment]
I haven't touched that code in many years. I'd welcome a pull request, 
though. :)

**Comment by skipmeister123** [comment]
@LoveBootCaptain Try the latest changes and let me know if the problem continues.  I just merged some downstream changes.

**Comment by pcercuei** [comment]
That's a OS/hardware problem, not an application problem.

**Comment by skipmeister123** [comment]
Thanks for jumping in, Paul.
